'use client';

import React from 'react';
import { Trash2, Edit2, AlertCircle } from 'lucide-react';
import { TemperatureEntry } from '../types';

interface TemperatureTableProps {
    data: TemperatureEntry[];
    onDelete: (id: string) => Promise<void>;
}

const TemperatureTable: React.FC<TemperatureTableProps> = ({ data, onDelete }) => {
    // Sort descending by date
    const sortedData = [...data].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    if (!sortedData.length) {
        return (
            <div className="text-center py-12 bg-white rounded-2xl border border-dashed border-gray-300">
                <p className="text-gray-500">Zatím žádné záznamy v historii.</p>
            </div>
        )
    }

    return (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-slate-100">
                    <thead className="bg-slate-50">
                        <tr>
                            <th scope="col" className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Datum</th>
                            <th scope="col" className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Teplota</th>
                            <th scope="col" className="px-6 py-4 text-right text-xs font-semibold text-slate-500 uppercase tracking-wider">Akce</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 bg-white">
                        {sortedData.map((entry) => (
                            <tr key={entry.id} className="hover:bg-slate-50/80 transition-colors group">
                                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-700">
                                    {new Date(entry.date).toLocaleDateString('cs-CZ')}
                                    <span className="text-xs text-gray-400 ml-2">
                                        {new Date(entry.date).toLocaleTimeString('cs-CZ', { hour: '2-digit', minute: '2-digit' })}
                                    </span>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap">
                                    {entry.value !== null ? (
                                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-sm font-medium bg-blue-50 text-blue-700">
                                            {entry.value.toFixed(1)} °C
                                        </span>
                                    ) : (
                                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-sm font-medium bg-gray-100 text-gray-800">
                                            Neměřeno
                                        </span>
                                    )}
                                    {entry.isAutoGenerated && (
                                        <span title="Automaticky vygenerováno" className="ml-2 text-amber-500 inline-block">
                                            <AlertCircle size={14} />
                                        </span>
                                    )}
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-right text-sm">
                                    <button
                                        onClick={() => onDelete(entry.id)}
                                        className="text-slate-400 hover:text-red-500 p-2 rounded-lg hover:bg-red-50 transition-all opacity-0 group-hover:opacity-100"
                                        title="Smazat záznam"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default TemperatureTable;
