-- Drop previous table if it exists (cleanup)
DROP TABLE IF EXISTS public.ai_nurse_survey_responses;

-- 1. Table for voting results (for statistics)
CREATE TABLE IF NOT EXISTS public.survey_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL, -- to link answers from one user
    question_text TEXT NOT NULL,
    selected_option TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table for leads/contacts
CREATE TABLE IF NOT EXISTS public.interest_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT, -- Changed to TEXT for flexibility, removed UNIQUE limitation to allow re-submission if needed, or handle in app code
    session_id UUID,
    status TEXT DEFAULT 'new', -- e.g. 'waiting_list'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.survey_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interest_leads ENABLE ROW LEVEL SECURITY;

-- Policies for public access (Survey is likely on landing page or accessible to non-logged-in users)
-- Allow anyone to insert results
CREATE POLICY "Allow public insert results" ON public.survey_results
    FOR INSERT
    WITH CHECK (true);

-- Allow anyone to insert leads
CREATE POLICY "Allow public insert leads" ON public.interest_leads
    FOR INSERT
    WITH CHECK (true);

-- Restrict SELECT to admins only (Service Role)
CREATE POLICY "Allow admin read results" ON public.survey_results
    FOR SELECT
    USING (auth.role() = 'service_role');

CREATE POLICY "Allow admin read leads" ON public.interest_leads
    FOR SELECT
    USING (auth.role() = 'service_role');
