
export interface TemperatureEntry {
    id: string;
    date: string; // ISO format
    value: number | null;
    isAutoGenerated: boolean;
    created_at?: string;
    user_id?: string;
}

export type Season = 'SUMMER' | 'WINTER' | 'TRANSITION';
